/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AplikasiUangKas;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author iyans018
 */
public class MainMenu extends javax.swing.JFrame {
    
    private Connection con;
    private Statement st;
    private ResultSet res;

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        koneksi();
        tampilMahasiswa();
        tampilPembayaran();
        
        Oktavian_pembayaranTanggalTextField.setText(LocalDateTime.now().format(DateTimeFormatter.ISO_DATE));
        Oktavian_mahasiswaLakiRadioButton.setActionCommand("L");
        Oktavian_mahasiswaPerempuanRadioButton.setActionCommand("P");
    }
    
    private void koneksi() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/apuk", "iyans018", "iyans018");
            st = con.createStatement();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void tampilMahasiswa() {
        DefaultTableModel tb = new DefaultTableModel();
        
        tb.addColumn("NIM");
        tb.addColumn("NAMA");
        tb.addColumn("KELAMIN");
        tb.addColumn("KELAS");
        
        Oktavian_mahasiswaTable.setModel(tb);
        
        try {
            res = st.executeQuery("SELECT * FROM mahasiswa");
            while (res.next()) {
                tb.addRow(new Object[]{
                    res.getString("nim"),
                    res.getString("nama"),
                    res.getString("jk"),
                    res.getString("kode_kelas")
                });
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void tampilPembayaran() {
        DefaultTableModel t = new DefaultTableModel();
        
        t.addColumn("KODE");
        t.addColumn("NIM");
        t.addColumn("NAMA");
        t.addColumn("KELAS");
        t.addColumn("BAYAR");
        t.addColumn("KEMBALIAN");
        t.addColumn("TANGGAL");
        
        Oktavian_pembayaranTable.setModel(t);
        
        try {
            res = st.executeQuery("SELECT * FROM pembayaran");
            while (res.next()) {
                t.addRow(new Object[]{
                    res.getString("kode_bayar"),
                    res.getString("nim"),
                    res.getString("nama"),
                    res.getString("ruang_kelas"),
                    res.getString("bayar"),
                    res.getString("kembalian"),
                    res.getString("tgl")
                });
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void kosongkan() {
        Oktavian_mahasiswaNimTextField.setText("");
        Oktavian_mahasiswaNamaTextField.setText("");
        Oktavian_mahasiswaLakiRadioButton.setSelected(false);
        Oktavian_mahasiswaPerempuanRadioButton.setSelected(false);
        Oktavian_mahasiswaKelasComboBox.setSelectedIndex(-1);
        Oktavian_pembayaranKodeTextField.setText("");
        Oktavian_pembayaranNimTextField.setText("");
        Oktavian_pembayaranNamaTextField.setText("");
        Oktavian_pembayaranKelasComboBox.setSelectedIndex(-1);
        Oktavian_pembayaranBayarTextField.setText("0");
        Oktavian_pembayaranKembalianTextField.setText("");
        Oktavian_pembayaranTanggalTextField.setText(LocalDateTime.now().format(DateTimeFormatter.ISO_DATE));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Oktavian_jkButtonGroup = new javax.swing.ButtonGroup();
        Oktavian_mainPanel = new javax.swing.JPanel();
        Oktavian_sidebarPanel = new javax.swing.JPanel();
        Oktavian_logoPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        Oktavian_homeMenuPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Oktavian_mahasiswaMenuPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Oktavian_pembayaranMenuPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Oktavian_cetakMenuPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Oktavian_keluarMenuPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Oktavian_bodyPanel = new javax.swing.JPanel();
        Oktavian_homePanel = new javax.swing.JPanel();
        Oktavian_homeHeaderPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Oktavian_mahasiswaPanel = new javax.swing.JPanel();
        Oktavian_mahasiswaHeaderPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Oktavian_mahasiswaNimTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Oktavian_mahasiswaNamaTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Oktavian_mahasiswaLakiRadioButton = new javax.swing.JRadioButton();
        Oktavian_mahasiswaPerempuanRadioButton = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        Oktavian_mahasiswaKelasComboBox = new javax.swing.JComboBox<>();
        Oktavian_mahasiswaTablePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Oktavian_mahasiswaTable = new javax.swing.JTable();
        Oktavian_mahasiswaSimpanButton = new javax.swing.JButton();
        Oktavian_mahasiswaEditButton = new javax.swing.JButton();
        Oktavian_mahasiswaDeleteButton = new javax.swing.JButton();
        Oktavian_mahasiswaSearchButton = new javax.swing.JButton();
        Oktavian_mahasiswaSearchTextField = new javax.swing.JTextField();
        Oktavian_pembayaranPanel = new javax.swing.JPanel();
        Oktavian_pembayaranHeaderPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Oktavian_pembayaranTanggalTextField = new javax.swing.JTextField();
        Oktavian_pembayaranKelasComboBox = new javax.swing.JComboBox<>();
        Oktavian_pembayaranNamaTextField = new javax.swing.JTextField();
        Oktavian_pembayaranNimTextField = new javax.swing.JTextField();
        Oktavian_pembayaranUangKasTextField = new javax.swing.JTextField();
        Oktavian_pembayaranBayarTextField = new javax.swing.JTextField();
        Oktavian_pembayaranKembalianTextField = new javax.swing.JTextField();
        Oktavian_pembayaranTablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Oktavian_pembayaranTable = new javax.swing.JTable();
        Oktavian_pembayaranSimpanButton = new javax.swing.JButton();
        Oktavian_pembayaranEditButton = new javax.swing.JButton();
        Oktavian_pembayaranDeleteButton = new javax.swing.JButton();
        Oktavian_pembayaranSearchTextField = new javax.swing.JTextField();
        Oktavian_pembayaranSearchButton = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        Oktavian_pembayaranKodeTextField = new javax.swing.JTextField();
        Oktavian_cetakPanel = new javax.swing.JPanel();
        Oktavian_cetakHeaderPanel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        Oktavian_cetakMahasiswaButton = new javax.swing.JButton();
        Oktavian_cetakPembayaranButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Pembayaran Uang Kas (APUK)");
        setPreferredSize(new java.awt.Dimension(900, 500));

        Oktavian_mainPanel.setBackground(new java.awt.Color(236, 240, 241));

        Oktavian_sidebarPanel.setBackground(new java.awt.Color(41, 128, 185));

        Oktavian_logoPanel.setBackground(new java.awt.Color(52, 73, 94));

        logoLabel.setFont(new java.awt.Font("Fira Code", 1, 24)); // NOI18N
        logoLabel.setForeground(java.awt.Color.white);
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/moneyLogo.png"))); // NOI18N
        logoLabel.setText("APUK");
        logoLabel.setIconTextGap(15);

        javax.swing.GroupLayout Oktavian_logoPanelLayout = new javax.swing.GroupLayout(Oktavian_logoPanel);
        Oktavian_logoPanel.setLayout(Oktavian_logoPanelLayout);
        Oktavian_logoPanelLayout.setHorizontalGroup(
            Oktavian_logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Oktavian_logoPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(logoLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Oktavian_logoPanelLayout.setVerticalGroup(
            Oktavian_logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Oktavian_logoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoLabel)
                .addContainerGap())
        );

        Oktavian_homeMenuPanel.setBackground(new java.awt.Color(52, 152, 219));
        Oktavian_homeMenuPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Oktavian_homeMenuPanelMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/homeIcon.png"))); // NOI18N
        jLabel5.setText("HOME");
        jLabel5.setIconTextGap(20);

        javax.swing.GroupLayout Oktavian_homeMenuPanelLayout = new javax.swing.GroupLayout(Oktavian_homeMenuPanel);
        Oktavian_homeMenuPanel.setLayout(Oktavian_homeMenuPanelLayout);
        Oktavian_homeMenuPanelLayout.setHorizontalGroup(
            Oktavian_homeMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Oktavian_homeMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Oktavian_homeMenuPanelLayout.setVerticalGroup(
            Oktavian_homeMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Oktavian_homeMenuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        Oktavian_mahasiswaMenuPanel.setBackground(new java.awt.Color(41, 128, 185));
        Oktavian_mahasiswaMenuPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Oktavian_mahasiswaMenuPanelMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gcapIcon.png"))); // NOI18N
        jLabel6.setText("MAHASISWA");
        jLabel6.setIconTextGap(20);

        javax.swing.GroupLayout Oktavian_mahasiswaMenuPanelLayout = new javax.swing.GroupLayout(Oktavian_mahasiswaMenuPanel);
        Oktavian_mahasiswaMenuPanel.setLayout(Oktavian_mahasiswaMenuPanelLayout);
        Oktavian_mahasiswaMenuPanelLayout.setHorizontalGroup(
            Oktavian_mahasiswaMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Oktavian_mahasiswaMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Oktavian_mahasiswaMenuPanelLayout.setVerticalGroup(
            Oktavian_mahasiswaMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Oktavian_mahasiswaMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Oktavian_pembayaranMenuPanel.setBackground(new java.awt.Color(41, 128, 185));
        Oktavian_pembayaranMenuPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Oktavian_pembayaranMenuPanelMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/moneyIcon.png"))); // NOI18N
        jLabel7.setText("PEMBAYARAN");
        jLabel7.setIconTextGap(20);

        javax.swing.GroupLayout Oktavian_pembayaranMenuPanelLayout = new javax.swing.GroupLayout(Oktavian_pembayaranMenuPanel);
        Oktavian_pembayaranMenuPanel.setLayout(Oktavian_pembayaranMenuPanelLayout);
        Oktavian_pembayaranMenuPanelLayout.setHorizontalGroup(
            Oktavian_pembayaranMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Oktavian_pembayaranMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        Oktavian_pembayaranMenuPanelLayout.setVerticalGroup(
            Oktavian_pembayaranMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Oktavian_pembayaranMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Oktavian_cetakMenuPanel.setBackground(new java.awt.Color(41, 128, 185));
        Oktavian_cetakMenuPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Oktavian_cetakMenuPanelMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/printerIcon.png"))); // NOI18N
        jLabel8.setText("CETAK");
        jLabel8.setIconTextGap(20);

        javax.swing.GroupLayout Oktavian_cetakMenuPanelLayout = new javax.swing.GroupLayout(Oktavian_cetakMenuPanel);
        Oktavian_cetakMenuPanel.setLayout(Oktavian_cetakMenuPanelLayout);
        Oktavian_cetakMenuPanelLayout.setHorizontalGroup(
            Oktavian_cetakMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Oktavian_cetakMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        Oktavian_cetakMenuPanelLayout.setVerticalGroup(
            Oktavian_cetakMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Oktavian_cetakMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Oktavian_keluarMenuPanel.setBackground(new java.awt.Color(41, 128, 185));
        Oktavian_keluarMenuPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Oktavian_keluarMenuPanelMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoutIcon.png"))); // NOI18N
        jLabel9.setText("KELUAR");
        jLabel9.setIconTextGap(20);

        javax.swing.GroupLayout Oktavian_keluarMenuPanelLayout = new javax.swing.GroupLayout(Oktavian_keluarMenuPanel);
        Oktavian_keluarMenuPanel.setLayout(Oktavian_keluarMenuPanelLayout);
        Oktavian_keluarMenuPanelLayout.setHorizontalGroup(
            Oktavian_keluarMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Oktavian_keluarMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        Oktavian_keluarMenuPanelLayout.setVerticalGroup(
            Oktavian_keluarMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Oktavian_keluarMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Oktavian_sidebarPanelLayout = new javax.swing.GroupLayout(Oktavian_sidebarPanel);
        Oktavian_sidebarPanel.setLayout(Oktavian_sidebarPanelLayout);
        Oktavian_sidebarPanelLayout.setHorizontalGroup(
            Oktavian_sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Oktavian_sidebarPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(Oktavian_sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Oktavian_logoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Oktavian_homeMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Oktavian_mahasiswaMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Oktavian_pembayaranMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Oktavian_cetakMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Oktavian_keluarMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        Oktavian_sidebarPanelLayout.setVerticalGroup(
            Oktavian_sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Oktavian_sidebarPanelLayout.createSequentialGroup()
                .addComponent(Oktavian_logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Oktavian_homeMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Oktavian_mahasiswaMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Oktavian_pembayaranMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Oktavian_cetakMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Oktavian_keluarMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Oktavian_bodyPanel.setLayout(new java.awt.CardLayout());

        Oktavian_homePanel.setBackground(new java.awt.Color(189, 195, 199));

        Oktavian_homeHeaderPanel.setBackground(java.awt.Color.white);
        Oktavian_homeHeaderPanel.setPreferredSize(new java.awt.Dimension(624, 60));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setText("APUK - HOME");

        javax.swing.GroupLayout Oktavian_homeHeaderPanelLayout = new javax.swing.GroupLayout(Oktavian_homeHeaderPanel);
        Oktavian_homeHeaderPanel.setLayout(Oktavian_homeHeaderPanelLayout);
        Oktavian_homeHeaderPanelLayout.setHorizontalGroup(
            Oktavian_homeHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Oktavian_homeHeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Oktavian_homeHeaderPanelLayout.setVerticalGroup(
            Oktavian_homeHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Oktavian_homeHeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel2.setText("Selamat Datang di APUK (Aplikasi Pembayaran Uang Kas)");

        jLabel23.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel23.setText("Dibuat oleh : Oktavian Aji Tyas Azis (181011402092)");

        javax.swing.GroupLayout Oktavian_homePanelLayout = new javax.swing.GroupLayout(Oktavian_homePanel);
        Oktavian_homePanel.setLayout(Oktavian_homePanelLayout);
        Oktavian_homePanelLayout.setHorizontalGroup(
            Oktavian_homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Oktavian_homeHeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
            .addGroup(Oktavian_homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Oktavian_homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel23))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        Oktavian_homePanelLayout.setVerticalGroup(
            Oktavian_homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Oktavian_homePanelLayout.createSequentialGroup()
                .addComponent(Oktavian_homeHeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addGap(0, 359, Short.MAX_VALUE))
        );

        Oktavian_bodyPanel.add(Oktavian_homePanel, "card2");

        Oktavian_mahasiswaPanel.setBackground(new java.awt.Color(189, 195, 199));

        Oktavian_mahasiswaHeaderPanel.setBackground(java.awt.Color.white);
        Oktavian_mahasiswaHeaderPanel.setPreferredSize(new java.awt.Dimension(624, 60));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setText("APUK - MAHASISWA");

        javax.swing.GroupLayout Oktavian_mahasiswaHeaderPanelLayout = new javax.swing.GroupLayout(Oktavian_mahasiswaHeaderPanel);
        Oktavian_mahasiswaHeaderPanel.setLayout(Oktavian_mahasiswaHeaderPanelLayout);
        Oktavian_mahasiswaHeaderPanelLayout.setHorizontalGroup(
            Oktavian_mahasiswaHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Oktavian_mahasiswaHeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(542, Short.MAX_VALUE))
        );
        Oktavian_mahasiswaHeaderPanelLayout.setVerticalGroup(
            Oktavian_mahasiswaHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Oktavian_mahasiswaHeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        jLabel4.setText("NIM");

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        jLabel10.setText("NAMA");

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        jLabel11.setText("JENIS KELAMIN");

        Oktavian_jkButtonGroup.add(Oktavian_mahasiswaLakiRadioButton);
        Oktavian_mahasiswaLakiRadioButton.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        Oktavian_mahasiswaLakiRadioButton.setText("laki-laki");

        Oktavian_jkButtonGroup.add(Oktavian_mahasiswaPerempuanRadioButton);
        Oktavian_mahasiswaPerempuanRadioButton.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        Oktavian_mahasiswaPerempuanRadioButton.setText("perempuan");

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        jLabel12.setText("KODE KELAS");

        Oktavian_mahasiswaKelasComboBox.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        Oktavian_mahasiswaKelasComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "05TPLP005", "05TPLP006", "05TPLP007", "05TPLP008" }));

        Oktavian_mahasiswaTablePanel.setLayout(new java.awt.CardLayout());

        Oktavian_mahasiswaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NIM", "NAMA", "KELAMIN", "KELAS"
            }
        ));
        Oktavian_mahasiswaTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Oktavian_mahasiswaTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Oktavian_mahasiswaTable);

        Oktavian_mahasiswaTablePanel.add(jScrollPane2, "card2");

        Oktavian_mahasiswaSimpanButton.setBackground(new java.awt.Color(41, 128, 185));
        Oktavian_mahasiswaSimpanButton.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        Oktavian_mahasiswaSimpanButton.setForeground(java.awt.Color.white);
        Oktavian_mahasiswaSimpanButton.setText("SIMPAN");
        Oktavian_mahasiswaSimpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Oktavian_mahasiswaSimpanButtonActionPerformed(evt);
            }
        });

        Oktavian_mahasiswaEditButton.setBackground(new java.awt.Color(241, 196, 15));
        Oktavian_mahasiswaEditButton.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        Oktavian_mahasiswaEditButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pencilIcon.png"))); // NOI18N
        Oktavian_mahasiswaEditButton.setPreferredSize(new java.awt.Dimension(36, 36));
        Oktavian_mahasiswaEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Oktavian_mahasiswaEditButtonActionPerformed(evt);
            }
        });

        Oktavian_mahasiswaDeleteButton.setBackground(new java.awt.Color(231, 76, 60));
        Oktavian_mahasiswaDeleteButton.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        Oktavian_mahasiswaDeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trashIcon.png"))); // NOI18N
        Oktavian_mahasiswaDeleteButton.setPreferredSize(new java.awt.Dimension(36, 36));
        Oktavian_mahasiswaDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Oktavian_mahasiswaDeleteButtonActionPerformed(evt);
            }
        });

        Oktavian_mahasiswaSearchButton.setBackground(new java.awt.Color(41, 128, 185));
        Oktavian_mahasiswaSearchButton.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        Oktavian_mahasiswaSearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/searchIcon.png"))); // NOI18N
        Oktavian_mahasiswaSearchButton.setPreferredSize(new java.awt.Dimension(36, 36));
        Oktavian_mahasiswaSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Oktavian_mahasiswaSearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Oktavian_mahasiswaPanelLayout = new javax.swing.GroupLayout(Oktavian_mahasiswaPanel);
        Oktavian_mahasiswaPanel.setLayout(Oktavian_mahasiswaPanelLayout);
        Oktavian_mahasiswaPanelLayout.setHorizontalGroup(
            Oktavian_mahasiswaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Oktavian_mahasiswaHeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
            .addGroup(Oktavian_mahasiswaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Oktavian_mahasiswaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(Oktavian_mahasiswaNimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(Oktavian_mahasiswaNamaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addGroup(Oktavian_mahasiswaPanelLayout.createSequentialGroup()
                        .addComponent(Oktavian_mahasiswaLakiRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Oktavian_mahasiswaPerempuanRadioButton))
                    .addComponent(jLabel12)
                    .addComponent(Oktavian_mahasiswaKelasComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Oktavian_mahasiswaSimpanButton))
                .addGap(18, 18, 18)
                .addGroup(Oktavian_mahasiswaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Oktavian_mahasiswaTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Oktavian_mahasiswaPanelLayout.createSequentialGroup()
                        .addComponent(Oktavian_mahasiswaEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Oktavian_mahasiswaDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Oktavian_mahasiswaSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Oktavian_mahasiswaSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        Oktavian_mahasiswaPanelLayout.setVerticalGroup(
            Oktavian_mahasiswaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Oktavian_mahasiswaPanelLayout.createSequentialGroup()
                .addComponent(Oktavian_mahasiswaHeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Oktavian_mahasiswaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Oktavian_mahasiswaPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Oktavian_mahasiswaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Oktavian_mahasiswaNimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Oktavian_mahasiswaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Oktavian_mahasiswaEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Oktavian_mahasiswaDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Oktavian_mahasiswaSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Oktavian_mahasiswaPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Oktavian_mahasiswaSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(Oktavian_mahasiswaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Oktavian_mahasiswaPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Oktavian_mahasiswaNamaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Oktavian_mahasiswaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Oktavian_mahasiswaLakiRadioButton)
                            .addComponent(Oktavian_mahasiswaPerempuanRadioButton))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Oktavian_mahasiswaKelasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Oktavian_mahasiswaSimpanButton)
                        .addGap(0, 63, Short.MAX_VALUE))
                    .addComponent(Oktavian_mahasiswaTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        Oktavian_bodyPanel.add(Oktavian_mahasiswaPanel, "card3");

        Oktavian_pembayaranPanel.setBackground(new java.awt.Color(189, 195, 199));

        Oktavian_pembayaranHeaderPanel.setBackground(java.awt.Color.white);
        Oktavian_pembayaranHeaderPanel.setPreferredSize(new java.awt.Dimension(624, 60));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel13.setText("APUK - PEMBAYARAN");

        javax.swing.GroupLayout Oktavian_pembayaranHeaderPanelLayout = new javax.swing.GroupLayout(Oktavian_pembayaranHeaderPanel);
        Oktavian_pembayaranHeaderPanel.setLayout(Oktavian_pembayaranHeaderPanelLayout);
        Oktavian_pembayaranHeaderPanelLayout.setHorizontalGroup(
            Oktavian_pembayaranHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Oktavian_pembayaranHeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(531, Short.MAX_VALUE))
        );
        Oktavian_pembayaranHeaderPanelLayout.setVerticalGroup(
            Oktavian_pembayaranHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Oktavian_pembayaranHeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        jLabel14.setText("NIM");

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        jLabel15.setText("NAMA");

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        jLabel16.setText("RUANG KELAS");

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        jLabel17.setText("UANG KAS");

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        jLabel18.setText("BAYAR");

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        jLabel19.setText("KEMBALIAN");

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        jLabel20.setText("TANGGAL");

        Oktavian_pembayaranKelasComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "05TPLP005", "05TPLP006", "05TPLP007", "05TPLP008" }));
        Oktavian_pembayaranKelasComboBox.setSelectedIndex(-1);

        Oktavian_pembayaranUangKasTextField.setEditable(false);
        Oktavian_pembayaranUangKasTextField.setText("1000");

        Oktavian_pembayaranBayarTextField.setText("0");

        Oktavian_pembayaranKembalianTextField.setEditable(false);
        Oktavian_pembayaranKembalianTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Oktavian_pembayaranKembalianTextFieldMouseClicked(evt);
            }
        });

        Oktavian_pembayaranTablePanel.setLayout(new java.awt.CardLayout());

        Oktavian_pembayaranTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "KODE", "NIM", "NAMA", "KELAS", "BAYAR", "KEMBALIAN", "TGL"
            }
        ));
        Oktavian_pembayaranTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Oktavian_pembayaranTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Oktavian_pembayaranTable);

        Oktavian_pembayaranTablePanel.add(jScrollPane1, "card2");

        Oktavian_pembayaranSimpanButton.setBackground(new java.awt.Color(41, 128, 185));
        Oktavian_pembayaranSimpanButton.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        Oktavian_pembayaranSimpanButton.setForeground(java.awt.Color.white);
        Oktavian_pembayaranSimpanButton.setText("SIMPAN");
        Oktavian_pembayaranSimpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Oktavian_pembayaranSimpanButtonActionPerformed(evt);
            }
        });

        Oktavian_pembayaranEditButton.setBackground(new java.awt.Color(241, 196, 15));
        Oktavian_pembayaranEditButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pencilIcon.png"))); // NOI18N
        Oktavian_pembayaranEditButton.setPreferredSize(new java.awt.Dimension(36, 36));
        Oktavian_pembayaranEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Oktavian_pembayaranEditButtonActionPerformed(evt);
            }
        });

        Oktavian_pembayaranDeleteButton.setBackground(new java.awt.Color(231, 76, 60));
        Oktavian_pembayaranDeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trashIcon.png"))); // NOI18N
        Oktavian_pembayaranDeleteButton.setPreferredSize(new java.awt.Dimension(36, 36));
        Oktavian_pembayaranDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Oktavian_pembayaranDeleteButtonActionPerformed(evt);
            }
        });

        Oktavian_pembayaranSearchButton.setBackground(new java.awt.Color(41, 128, 185));
        Oktavian_pembayaranSearchButton.setForeground(java.awt.Color.white);
        Oktavian_pembayaranSearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/searchIcon.png"))); // NOI18N
        Oktavian_pembayaranSearchButton.setPreferredSize(new java.awt.Dimension(36, 36));
        Oktavian_pembayaranSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Oktavian_pembayaranSearchButtonActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        jLabel22.setText("KODE");

        javax.swing.GroupLayout Oktavian_pembayaranPanelLayout = new javax.swing.GroupLayout(Oktavian_pembayaranPanel);
        Oktavian_pembayaranPanel.setLayout(Oktavian_pembayaranPanelLayout);
        Oktavian_pembayaranPanelLayout.setHorizontalGroup(
            Oktavian_pembayaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Oktavian_pembayaranHeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
            .addGroup(Oktavian_pembayaranPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Oktavian_pembayaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Oktavian_pembayaranPanelLayout.createSequentialGroup()
                        .addGroup(Oktavian_pembayaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Oktavian_pembayaranTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Oktavian_pembayaranPanelLayout.createSequentialGroup()
                                .addGroup(Oktavian_pembayaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(Oktavian_pembayaranPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(9, 9, 9)
                                        .addComponent(Oktavian_pembayaranKelasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Oktavian_pembayaranPanelLayout.createSequentialGroup()
                                        .addComponent(Oktavian_pembayaranSimpanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Oktavian_pembayaranEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Oktavian_pembayaranDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(32, 32, 32)
                                .addComponent(Oktavian_pembayaranSearchTextField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Oktavian_pembayaranSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Oktavian_pembayaranPanelLayout.createSequentialGroup()
                        .addGroup(Oktavian_pembayaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel22))
                        .addGap(65, 65, 65)
                        .addGroup(Oktavian_pembayaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Oktavian_pembayaranNimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Oktavian_pembayaranNamaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Oktavian_pembayaranKodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Oktavian_pembayaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Oktavian_pembayaranPanelLayout.createSequentialGroup()
                                .addGroup(Oktavian_pembayaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addGap(21, 21, 21)
                                .addGroup(Oktavian_pembayaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Oktavian_pembayaranUangKasTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(Oktavian_pembayaranBayarTextField)))
                            .addGroup(Oktavian_pembayaranPanelLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(12, 12, 12)
                                .addComponent(Oktavian_pembayaranKembalianTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Oktavian_pembayaranPanelLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(26, 26, 26)
                                .addComponent(Oktavian_pembayaranTanggalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(134, 134, 134))))
        );
        Oktavian_pembayaranPanelLayout.setVerticalGroup(
            Oktavian_pembayaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Oktavian_pembayaranPanelLayout.createSequentialGroup()
                .addComponent(Oktavian_pembayaranHeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(Oktavian_pembayaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(Oktavian_pembayaranUangKasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(Oktavian_pembayaranKodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Oktavian_pembayaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(Oktavian_pembayaranBayarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(Oktavian_pembayaranNimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Oktavian_pembayaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Oktavian_pembayaranNamaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(Oktavian_pembayaranKembalianTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Oktavian_pembayaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(Oktavian_pembayaranKelasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(Oktavian_pembayaranTanggalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(Oktavian_pembayaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Oktavian_pembayaranSearchTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Oktavian_pembayaranSearchButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Oktavian_pembayaranEditButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Oktavian_pembayaranDeleteButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Oktavian_pembayaranSimpanButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Oktavian_pembayaranTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Oktavian_bodyPanel.add(Oktavian_pembayaranPanel, "card4");

        Oktavian_cetakPanel.setBackground(new java.awt.Color(189, 195, 199));

        Oktavian_cetakHeaderPanel.setBackground(java.awt.Color.white);
        Oktavian_cetakHeaderPanel.setPreferredSize(new java.awt.Dimension(624, 60));

        jLabel21.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel21.setText("APUK - CETAK");

        javax.swing.GroupLayout Oktavian_cetakHeaderPanelLayout = new javax.swing.GroupLayout(Oktavian_cetakHeaderPanel);
        Oktavian_cetakHeaderPanel.setLayout(Oktavian_cetakHeaderPanelLayout);
        Oktavian_cetakHeaderPanelLayout.setHorizontalGroup(
            Oktavian_cetakHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Oktavian_cetakHeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addContainerGap(586, Short.MAX_VALUE))
        );
        Oktavian_cetakHeaderPanelLayout.setVerticalGroup(
            Oktavian_cetakHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Oktavian_cetakHeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Oktavian_cetakMahasiswaButton.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        Oktavian_cetakMahasiswaButton.setText("CETAK DATA MAHASISWA");
        Oktavian_cetakMahasiswaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Oktavian_cetakMahasiswaButtonActionPerformed(evt);
            }
        });

        Oktavian_cetakPembayaranButton.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        Oktavian_cetakPembayaranButton.setText("CETAK DATA PEMBAYARAN");
        Oktavian_cetakPembayaranButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Oktavian_cetakPembayaranButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Oktavian_cetakPanelLayout = new javax.swing.GroupLayout(Oktavian_cetakPanel);
        Oktavian_cetakPanel.setLayout(Oktavian_cetakPanelLayout);
        Oktavian_cetakPanelLayout.setHorizontalGroup(
            Oktavian_cetakPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Oktavian_cetakHeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
            .addGroup(Oktavian_cetakPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Oktavian_cetakMahasiswaButton)
                .addGap(106, 106, 106)
                .addComponent(Oktavian_cetakPembayaranButton)
                .addGap(94, 94, 94))
        );
        Oktavian_cetakPanelLayout.setVerticalGroup(
            Oktavian_cetakPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Oktavian_cetakPanelLayout.createSequentialGroup()
                .addComponent(Oktavian_cetakHeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133)
                .addGroup(Oktavian_cetakPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Oktavian_cetakMahasiswaButton)
                    .addComponent(Oktavian_cetakPembayaranButton))
                .addGap(0, 293, Short.MAX_VALUE))
        );

        Oktavian_bodyPanel.add(Oktavian_cetakPanel, "card5");

        javax.swing.GroupLayout Oktavian_mainPanelLayout = new javax.swing.GroupLayout(Oktavian_mainPanel);
        Oktavian_mainPanel.setLayout(Oktavian_mainPanelLayout);
        Oktavian_mainPanelLayout.setHorizontalGroup(
            Oktavian_mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Oktavian_mainPanelLayout.createSequentialGroup()
                .addComponent(Oktavian_sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Oktavian_bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Oktavian_mainPanelLayout.setVerticalGroup(
            Oktavian_mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Oktavian_bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Oktavian_sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Oktavian_mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Oktavian_mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Oktavian_homeMenuPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Oktavian_homeMenuPanelMouseClicked
        // TODO add your handling code here:
        //remove panel
        Oktavian_bodyPanel.removeAll();
        Oktavian_bodyPanel.repaint();
        Oktavian_bodyPanel.revalidate();
        
        //add panel
        Oktavian_bodyPanel.add(Oktavian_homePanel);
        Oktavian_bodyPanel.repaint();
        Oktavian_bodyPanel.revalidate();
        
        setColor(Oktavian_homeMenuPanel);
        resetColor(Oktavian_mahasiswaMenuPanel);
        resetColor(Oktavian_pembayaranMenuPanel);
        resetColor(Oktavian_cetakMenuPanel);
        resetColor(Oktavian_keluarMenuPanel);
    }//GEN-LAST:event_Oktavian_homeMenuPanelMouseClicked

    private void Oktavian_mahasiswaMenuPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Oktavian_mahasiswaMenuPanelMouseClicked
        // TODO add your handling code here:
        //remove panel
        Oktavian_bodyPanel.removeAll();
        Oktavian_bodyPanel.repaint();
        Oktavian_bodyPanel.revalidate();
        
        //add panel
        Oktavian_bodyPanel.add(Oktavian_mahasiswaPanel);
        Oktavian_bodyPanel.repaint();
        Oktavian_bodyPanel.revalidate();
        
        setColor(Oktavian_mahasiswaMenuPanel);
        resetColor(Oktavian_homeMenuPanel);
        resetColor(Oktavian_pembayaranMenuPanel);
        resetColor(Oktavian_cetakMenuPanel);
        resetColor(Oktavian_keluarMenuPanel);
    }//GEN-LAST:event_Oktavian_mahasiswaMenuPanelMouseClicked

    private void Oktavian_pembayaranMenuPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Oktavian_pembayaranMenuPanelMouseClicked
        // TODO add your handling code here:
        //remove panel
        Oktavian_bodyPanel.removeAll();
        Oktavian_bodyPanel.repaint();
        Oktavian_bodyPanel.revalidate();
        
        //add panel
        Oktavian_bodyPanel.add(Oktavian_pembayaranPanel);
        Oktavian_bodyPanel.repaint();
        Oktavian_bodyPanel.revalidate();
        
        setColor(Oktavian_pembayaranMenuPanel);
        resetColor(Oktavian_homeMenuPanel);
        resetColor(Oktavian_mahasiswaMenuPanel);
        resetColor(Oktavian_cetakMenuPanel);
        resetColor(Oktavian_keluarMenuPanel);
    }//GEN-LAST:event_Oktavian_pembayaranMenuPanelMouseClicked

    private void Oktavian_cetakMenuPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Oktavian_cetakMenuPanelMouseClicked
        // TODO add your handling code here:
        //remove panel
        Oktavian_bodyPanel.removeAll();
        Oktavian_bodyPanel.repaint();
        Oktavian_bodyPanel.revalidate();
        
        //add panel
        Oktavian_bodyPanel.add(Oktavian_cetakPanel);
        Oktavian_bodyPanel.repaint();
        Oktavian_bodyPanel.revalidate();
        
        setColor(Oktavian_cetakMenuPanel);
        resetColor(Oktavian_homeMenuPanel);
        resetColor(Oktavian_mahasiswaMenuPanel);
        resetColor(Oktavian_pembayaranMenuPanel);
        resetColor(Oktavian_keluarMenuPanel);
    }//GEN-LAST:event_Oktavian_cetakMenuPanelMouseClicked

    private void Oktavian_keluarMenuPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Oktavian_keluarMenuPanelMouseClicked
        // TODO add your handling code here:
        setColor(Oktavian_keluarMenuPanel);
        resetColor(Oktavian_homeMenuPanel);
        resetColor(Oktavian_mahasiswaMenuPanel);
        resetColor(Oktavian_pembayaranMenuPanel);
        resetColor(Oktavian_cetakMenuPanel);
        
        int keluar = JOptionPane.showConfirmDialog(
                rootPane,
                "Anda yakin ingin keluar?",
                "Confirmation",
                JOptionPane.YES_NO_OPTION
        );
       
        if (keluar == 0) {
            System.exit(1);
        }
    }//GEN-LAST:event_Oktavian_keluarMenuPanelMouseClicked

    private void Oktavian_mahasiswaSimpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Oktavian_mahasiswaSimpanButtonActionPerformed
        // TODO add your handling code here:
        try {
            st.executeUpdate("INSERT INTO mahasiswa VALUES("
                    + "'" + Oktavian_mahasiswaNimTextField.getText() + "',"
                    + "'" + Oktavian_mahasiswaNamaTextField.getText() + "',"
                    + "'" + Oktavian_jkButtonGroup.getSelection().getActionCommand() + "',"
                    + "'" + Oktavian_mahasiswaKelasComboBox.getSelectedItem() + "')"
            );
            JOptionPane.showMessageDialog(rootPane, "Berhasil menambahkan data.");
            kosongkan();
            tampilMahasiswa();
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "Gagal menambahkan data! " + e);
        }
    }//GEN-LAST:event_Oktavian_mahasiswaSimpanButtonActionPerformed

    private void Oktavian_pembayaranSimpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Oktavian_pembayaranSimpanButtonActionPerformed
        // TODO add your handling code here:
        try {
            st.executeUpdate(
                    "INSERT INTO pembayaran VALUES"
                    + "("
                        + "'" + Oktavian_pembayaranKodeTextField.getText() + "',"
                        + "'" + Oktavian_pembayaranNimTextField.getText() + "',"
                        + "'" + Oktavian_pembayaranNamaTextField.getText() + "',"
                        + "'" + Oktavian_pembayaranKelasComboBox.getSelectedItem() + "',"
                        + "'" + Oktavian_pembayaranBayarTextField.getText() + "',"
                        + "'" + Oktavian_pembayaranKembalianTextField.getText() + "',"
                        + "'" + Oktavian_pembayaranTanggalTextField.getText() + "'"
                    + ")"
            );
            JOptionPane.showMessageDialog(rootPane, "Berhasil menambahkan data.");
            kosongkan();
            tampilPembayaran();
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "Gagal menambahkan data! " + e);
        }
    }//GEN-LAST:event_Oktavian_pembayaranSimpanButtonActionPerformed

    private void Oktavian_pembayaranKembalianTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Oktavian_pembayaranKembalianTextFieldMouseClicked
        // TODO add your handling code here:
        float bayar = Float.parseFloat(Oktavian_pembayaranBayarTextField.getText());
        float uangkas = Float.parseFloat(Oktavian_pembayaranUangKasTextField.getText());
        float kembalian = bayar - uangkas;
        
        Oktavian_pembayaranKembalianTextField.setText(String.valueOf(kembalian));
    }//GEN-LAST:event_Oktavian_pembayaranKembalianTextFieldMouseClicked

    private void Oktavian_mahasiswaTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Oktavian_mahasiswaTableMouseClicked
        // TODO add your handling code here:
        int i = Oktavian_mahasiswaTable.getSelectedRow();
        String kelamin = String.valueOf(Oktavian_mahasiswaTable.getValueAt(i, 2));
        
        
        Oktavian_mahasiswaNimTextField.setText(String.valueOf(Oktavian_mahasiswaTable.getValueAt(i, 0)));
        Oktavian_mahasiswaNamaTextField.setText(String.valueOf(Oktavian_mahasiswaTable.getValueAt(i, 1)));
        if (kelamin.equals("L")) {
            Oktavian_mahasiswaLakiRadioButton.setSelected(true);
        } else {
            Oktavian_mahasiswaPerempuanRadioButton.setSelected(true);
        }
        Oktavian_mahasiswaKelasComboBox.setSelectedItem(String.valueOf(Oktavian_mahasiswaTable.getValueAt(i, 3)));
    }//GEN-LAST:event_Oktavian_mahasiswaTableMouseClicked

    private void Oktavian_mahasiswaEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Oktavian_mahasiswaEditButtonActionPerformed
        // TODO add your handling code here:
        try {
            st.executeUpdate("UPDATE mahasiswa SET "
                    + "nim = '" + Oktavian_mahasiswaNimTextField.getText() + "',"
                    + "nama = '" + Oktavian_mahasiswaNamaTextField.getText() + "',"
                    + "jk = '" + Oktavian_jkButtonGroup.getSelection().getActionCommand() + "',"
                    + "kode_kelas = '" + Oktavian_mahasiswaKelasComboBox.getSelectedItem() + "' "
                    + "WHERE nim = '" + Oktavian_mahasiswaNimTextField.getText() + "'"
            );
            JOptionPane.showMessageDialog(rootPane, "Berhasil update data.");
            kosongkan();
            tampilMahasiswa();
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "Gagal update data! " + e);
        }
    }//GEN-LAST:event_Oktavian_mahasiswaEditButtonActionPerformed

    private void Oktavian_mahasiswaDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Oktavian_mahasiswaDeleteButtonActionPerformed
        // TODO add your handling code here:
        int delete = JOptionPane.showConfirmDialog(
                rootPane,
                "Anda yakin ingin menghapus data ini?",
                "Confirmation",
                JOptionPane.YES_NO_OPTION
        );
       
        if (delete == 0) {
            try {
                String sql = "DELETE FROM mahasiswa WHERE nim = '"
                        + Oktavian_mahasiswaNimTextField.getText() + "'";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Berhasil delete data.");
                kosongkan();
                tampilMahasiswa();
            } catch(HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(rootPane, "Gagal delete data! " + e);
            }
        }
    }//GEN-LAST:event_Oktavian_mahasiswaDeleteButtonActionPerformed

    private void Oktavian_mahasiswaSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Oktavian_mahasiswaSearchButtonActionPerformed
        // TODO add your handling code here:
        try {
            res = st.executeQuery("SELECT * FROM mahasiswa WHERE nim = '"
                    + Oktavian_mahasiswaSearchTextField.getText() + "'"
            );
            while(res.next()) {
                String kelamin = res.getString("jk");
                
                Oktavian_mahasiswaNimTextField.setText(res.getString("nim"));
                Oktavian_mahasiswaNamaTextField.setText(res.getString("nama"));
                if (kelamin.equals("L")) {
                    Oktavian_mahasiswaLakiRadioButton.setSelected(true);
                } else {
                    Oktavian_mahasiswaPerempuanRadioButton.setSelected(true);
                }
                Oktavian_mahasiswaKelasComboBox.setSelectedItem(res.getString("kode_kelas"));
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_Oktavian_mahasiswaSearchButtonActionPerformed

    private void Oktavian_pembayaranTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Oktavian_pembayaranTableMouseClicked
        // TODO add your handling code here:
        int i = Oktavian_pembayaranTable.getSelectedRow();
        
        Oktavian_pembayaranKodeTextField.setText(String.valueOf(Oktavian_pembayaranTable.getValueAt(i, 0)));
        Oktavian_pembayaranNimTextField.setText(String.valueOf(Oktavian_pembayaranTable.getValueAt(i, 1)));
        Oktavian_pembayaranNamaTextField.setText(String.valueOf(Oktavian_pembayaranTable.getValueAt(i, 2)));
        Oktavian_pembayaranKelasComboBox.setSelectedItem(String.valueOf(Oktavian_pembayaranTable.getValueAt(i, 3)));
        Oktavian_pembayaranBayarTextField.setText(String.valueOf(Oktavian_pembayaranTable.getValueAt(i, 4)));
        Oktavian_pembayaranKembalianTextField.setText(String.valueOf(Oktavian_pembayaranTable.getValueAt(i, 5)));
        Oktavian_pembayaranTanggalTextField.setText(String.valueOf(Oktavian_pembayaranTable.getValueAt(i, 6)));
    }//GEN-LAST:event_Oktavian_pembayaranTableMouseClicked

    private void Oktavian_pembayaranEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Oktavian_pembayaranEditButtonActionPerformed
        // TODO add your handling code here:
        try {
            st.executeUpdate("UPDATE pembayaran SET "
                    + "nim = '" + Oktavian_pembayaranNimTextField.getText() + "',"
                    + "nama = '"+ Oktavian_pembayaranNamaTextField.getText() + "',"
                    + "ruang_kelas = '" + Oktavian_pembayaranKelasComboBox.getSelectedItem() + "',"
                    + "bayar = '" + Oktavian_pembayaranBayarTextField.getText() + "',"
                    + "kembalian = '" + Oktavian_pembayaranKembalianTextField.getText() + "',"
                    + "tgl = '" + Oktavian_pembayaranTanggalTextField.getText() + "' "
                    + "WHERE kode_bayar = '" + Oktavian_pembayaranKodeTextField.getText() + "'"
            );
            JOptionPane.showMessageDialog(rootPane, "Berhasil update data.");
            kosongkan();
            tampilPembayaran();
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "Gagal update data! " + e);
        }
    }//GEN-LAST:event_Oktavian_pembayaranEditButtonActionPerformed

    private void Oktavian_pembayaranDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Oktavian_pembayaranDeleteButtonActionPerformed
        // TODO add your handling code here:
        int delete = JOptionPane.showConfirmDialog(
                rootPane,
                "Anda yakin ingin menghapus data ini?",
                "Confirmation",
                JOptionPane.YES_NO_OPTION
        );
       
        if (delete == 0) {
            try {
                String sql = "DELETE FROM pembayaran WHERE kode_bayar = '"
                        + Oktavian_pembayaranKodeTextField.getText() + "'";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Berhasil delete data.");
                kosongkan();
                tampilPembayaran();
            } catch(HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(rootPane, "Gagal delete data! " + e);
            }
        }
    }//GEN-LAST:event_Oktavian_pembayaranDeleteButtonActionPerformed

    private void Oktavian_pembayaranSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Oktavian_pembayaranSearchButtonActionPerformed
        // TODO add your handling code here:
        try {
            res = st.executeQuery("SELECT * FROM pembayaran WHERE kode_bayar = '"
                    + Oktavian_pembayaranSearchTextField.getText() + "'"
            );
            while(res.next()) {
                Oktavian_pembayaranKodeTextField.setText(res.getString("kode_bayar"));
                Oktavian_pembayaranNimTextField.setText(res.getString("nim"));
                Oktavian_pembayaranNamaTextField.setText(res.getString("nama"));
                Oktavian_pembayaranKelasComboBox.setSelectedItem(res.getString("ruang_kelas"));
                Oktavian_pembayaranBayarTextField.setText(res.getString("bayar"));
                Oktavian_pembayaranKembalianTextField.setText(res.getString("kembalian"));
                Oktavian_pembayaranTanggalTextField.setText(res.getString("tgl"));
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_Oktavian_pembayaranSearchButtonActionPerformed

    private void Oktavian_cetakMahasiswaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Oktavian_cetakMahasiswaButtonActionPerformed
        // TODO add your handling code here:
        try {
            String report = "/home/iyans018/Projects/Netbeans/Aplikasi Uang Kas/src/mahasiswaReport/MahasiswaReport.jrxml";
            JasperDesign desain = JRXmlLoader.load(report);
            JasperReport jspReport = JasperCompileManager.compileReport(desain);
            res = st.executeQuery("SELECT * FROM mahasiswa");
            JRResultSetDataSource resultSetDataSource = new JRResultSetDataSource(res);
            JasperPrint jspPrint = JasperFillManager.fillReport(jspReport, new HashMap(), resultSetDataSource);
            JasperViewer.viewReport(jspPrint, false);
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Gagal mencetak " + ex);
        }
    }//GEN-LAST:event_Oktavian_cetakMahasiswaButtonActionPerformed

    private void Oktavian_cetakPembayaranButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Oktavian_cetakPembayaranButtonActionPerformed
        // TODO add your handling code here:
        try {
            String report = "/home/iyans018/Projects/Netbeans/Aplikasi Uang Kas/src/pembayaranReport/PembayaranReport.jrxml";
            JasperDesign desain = JRXmlLoader.load(report);
            JasperReport jspReport = JasperCompileManager.compileReport(desain);
            res = st.executeQuery("SELECT * FROM pembayaran");
            JRResultSetDataSource resultSetDataSource = new JRResultSetDataSource(res);
            JasperPrint jspPrint = JasperFillManager.fillReport(jspReport, new HashMap(), resultSetDataSource);
            JasperViewer.viewReport(jspPrint, false);
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Gagal mencetak " + ex);
        }
    }//GEN-LAST:event_Oktavian_cetakPembayaranButtonActionPerformed

    
    void setColor(JPanel panel) {
        panel.setBackground(new Color(52, 152, 219));
    }
    
    void resetColor(JPanel panel) {
        panel.setBackground(new Color(41, 128, 185));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Oktavian_bodyPanel;
    private javax.swing.JPanel Oktavian_cetakHeaderPanel;
    private javax.swing.JButton Oktavian_cetakMahasiswaButton;
    private javax.swing.JPanel Oktavian_cetakMenuPanel;
    private javax.swing.JPanel Oktavian_cetakPanel;
    private javax.swing.JButton Oktavian_cetakPembayaranButton;
    private javax.swing.JPanel Oktavian_homeHeaderPanel;
    private javax.swing.JPanel Oktavian_homeMenuPanel;
    private javax.swing.JPanel Oktavian_homePanel;
    private javax.swing.ButtonGroup Oktavian_jkButtonGroup;
    private javax.swing.JPanel Oktavian_keluarMenuPanel;
    private javax.swing.JPanel Oktavian_logoPanel;
    private javax.swing.JButton Oktavian_mahasiswaDeleteButton;
    private javax.swing.JButton Oktavian_mahasiswaEditButton;
    private javax.swing.JPanel Oktavian_mahasiswaHeaderPanel;
    private javax.swing.JComboBox<String> Oktavian_mahasiswaKelasComboBox;
    private javax.swing.JRadioButton Oktavian_mahasiswaLakiRadioButton;
    private javax.swing.JPanel Oktavian_mahasiswaMenuPanel;
    private javax.swing.JTextField Oktavian_mahasiswaNamaTextField;
    private javax.swing.JTextField Oktavian_mahasiswaNimTextField;
    private javax.swing.JPanel Oktavian_mahasiswaPanel;
    private javax.swing.JRadioButton Oktavian_mahasiswaPerempuanRadioButton;
    private javax.swing.JButton Oktavian_mahasiswaSearchButton;
    private javax.swing.JTextField Oktavian_mahasiswaSearchTextField;
    private javax.swing.JButton Oktavian_mahasiswaSimpanButton;
    private javax.swing.JTable Oktavian_mahasiswaTable;
    private javax.swing.JPanel Oktavian_mahasiswaTablePanel;
    private javax.swing.JPanel Oktavian_mainPanel;
    private javax.swing.JTextField Oktavian_pembayaranBayarTextField;
    private javax.swing.JButton Oktavian_pembayaranDeleteButton;
    private javax.swing.JButton Oktavian_pembayaranEditButton;
    private javax.swing.JPanel Oktavian_pembayaranHeaderPanel;
    private javax.swing.JComboBox<String> Oktavian_pembayaranKelasComboBox;
    private javax.swing.JTextField Oktavian_pembayaranKembalianTextField;
    private javax.swing.JTextField Oktavian_pembayaranKodeTextField;
    private javax.swing.JPanel Oktavian_pembayaranMenuPanel;
    private javax.swing.JTextField Oktavian_pembayaranNamaTextField;
    private javax.swing.JTextField Oktavian_pembayaranNimTextField;
    private javax.swing.JPanel Oktavian_pembayaranPanel;
    private javax.swing.JButton Oktavian_pembayaranSearchButton;
    private javax.swing.JTextField Oktavian_pembayaranSearchTextField;
    private javax.swing.JButton Oktavian_pembayaranSimpanButton;
    private javax.swing.JTable Oktavian_pembayaranTable;
    private javax.swing.JPanel Oktavian_pembayaranTablePanel;
    private javax.swing.JTextField Oktavian_pembayaranTanggalTextField;
    private javax.swing.JTextField Oktavian_pembayaranUangKasTextField;
    private javax.swing.JPanel Oktavian_sidebarPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel logoLabel;
    // End of variables declaration//GEN-END:variables
}
